version: '3.4'

services:
  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

volumes:
  postgres_catalog:

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
