# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices"
      dockerfile: "Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basket.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices\\Basket.API:/app:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices:/src:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices"
      dockerfile: "Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices\\Catalog.API:/app:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices:/src:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices"
      dockerfile: "Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discountgrpc:dev"
    ports: []
    volumes:
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices\\Discount.Grpc:/app:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\RiderProjects\\LearningMicroservices:/src:rw"
    - "C:\\Users\\Alexey.Kolomeitsev\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
